### ISSUE TITLE
My album's collage shows 4 albums from different artists, my artists collage still shows only one artist.

### ISSUE THREAD

**Issue by KR0WLEY** [SongStitch/song-stitch#264]
i have listened to 4 different artists this week, and 4 different albums
but my artist collage doesn't seem to update, apparently it just gets the URL from the first collage i did today. loads so fast and returns the same collage as today's' first, showing 1  artist.
But if I change any option, it generates a new and updated image. :/
website, google chrome.

**Comment by BradLewis** [comment]
Hello! We cache the generated collages to allow them to be shared easily without needing to regenerate them and have them be different. This will cache the images for 2 hours. As you noticed, this applies to each unique combination of options, so by changing them it'll regenerate the image. We can look into adding a way to bypass this cache if you would like to update it during that 2 hour period?

**Comment by BradLewis** [comment]
We have implemented a change to the caching behaviour, so that now when you press "generate", it will always generate a new collage based on the latest data. The URL generated for the collage will still use the cached image for 2 hours after it has been generated.

**Comment by KR0WLEY** [comment]
> We have implemented a change to the caching behaviour, so that now when you press "generate", it will always generate a new collage based on the latest data. The URL generated for the collage will still use the cached image for 2 hours after it has been generated.

![image](https://github.com/SongStitch/song-stitch/assets/50808176/f02fc2c5-650f-4fec-b836-7bbd3a8c5643)
Hey, it is now using the picture of 1 artist to various artists in the chart, in this case, the artist in others' pictures is 'Bones'
