### ISSUE TITLE
the chart is using same artist image for other artists.

### ISSUE THREAD

**Issue by KR0WLEY** [SongStitch/song-stitch#289]
![image](https://github.com/SongStitch/song-stitch/assets/50808176/caa661b2-fb63-4266-ac07-c495782f049b)
it happens **on the 2nd image generation and so on**, on the first everything is okay.

**Comment by BradLewis** [comment]
Hello! Thanks for raising this. We were able to quickly find the cause and fix this issue.

**Comment by KR0WLEY** [comment]
Nice, your chart generator is the best-looking!

**Comment by KR0WLEY** [comment]
Can i make a discord chart generator scrapping your website?

**Comment by BradLewis** [comment]
Yeah go for it! You should be able to just use the API directly to generate the collages.
