### ISSUE TITLE
Breaks on non-latin characters

### ISSUE THREAD

**Issue by yayuyokitano** [SongStitch/song-stitch#47]
Need fallback fonts that support a wider variety of characters.
Example:
![image](https://github.com/SongStitch/song-stitch/assets/69117606/ec545c00-3901-4926-bdac-b3ae72e78f3c)

**Comment by BradLewis** [comment]
Thanks for raising this! I'll work to get this fixed asap.

**Comment by BradLewis** [comment]
Should now be resolved :)
